#!/bin/bash

#Vê se tem privilégio de ROOT
if [ "$EUID" -ne 0 ]
  then echo "Você deve ter privilégios de root para executar o "
  read
  exit
fi;

add-apt-repository ppa:transmissionbt/ppa #adiciona o ppa do transmission

apt update
apt upgrade
apt install -y gcc nodejs git npm synaptic brasero flameshot snapd
snap install mailspring postman spotify #tirei o spotify porque ja tenho instalado sem ser snap
snap install code --classic #instala  o vscode
snap install discord --classic #instala o discord 
apt autoremove -y
npm install -g nodemon
printf '\n\n\n\n\n\n\nPor favor reinicie o computador para finalizar a instalação dos programas\n\n'
